services:
  nodeapp:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - frontend
      - backend 
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=nodeapp
    networks:
      - backend
    volumes:
      - mydata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    networks:
      - frontend    

networks:
  backend:
  frontend:
volumes:
  mydata: